# Welcome to Jekyll!
theme: jekyll-theme-so-simple

# Site Author
# author:
#   name: Michael Rose
#   picture: /images/michael-rose-photo.jpg
#   email:
#   twitter: mmistakes
#   links:
#     - title: Linkedin
#       url: https://www.linkedin.com/in/tarek-el-gendy/
#       icon: fab fa-instagram
#     - title: GitHub
#       url: https://github.com/mmistakes
#       icon: fab fa-github-square
